name: Build GDAL SWIG bindings

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin swig g++ make cmake libproj-dev libgdal-dev libnetcdf-dev libhdf5-dev

      - name: Download GDAL source code
        run: |
          wget https://github.com/OSGeo/gdal/archive/refs/tags/v3.6.2.tar.gz
          tar -xf v3.6.2.tar.gz
          mv gdal-3.6.2 gdal

      - name: Build GDAL
        run: |
          cd gdal
          mkdir build
          cd build
          cmake .. -DBUILD_SHARED_LIBS=ON -DWITH_JAVA=ON -DCMAKE_PREFIX_PATH=$PROJ_DIR -DCMAKE_INSTALL_PREFIX=/usr/local/
          make -j$(nproc)
          sudo make install

      - name: Build SWIG Bindings
        run: |
          cd gdal/swig/java
          make java

      - name: Compile SO file
        run: |
          cd gdal/swig/java
          g++ -shared -o libgdal.so libgdal_wrap.o -L/usr/lib -lgdal

      - name: Create artifacts
        run: |
          mkdir artifacts
          cp gdal/swig/java/libgdal.so artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gdal-java-bindings
          path: artifacts/